#!/usr/bin/env bash

set -e

main() {
	send tutorial
	nvim .
}

# @cmd Launches and setups the tutorial folder
tutorial() {
	cd os-tutorial/ && nvim .
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
